### ISSUE TITLE
[Data] Duplicate entries in Pinterest dataset

### ISSUE THREAD

**Issue by ghost** [Refefer/cloverleaf#5]
Verify with:

```bash
zcat pinterest.edges.gz | sort | uniq -cd
```

Example on line 30:

```
user  1 board 30  1
user  1 board 31  1
user  1 board 31  1
user  1 board 32  1
user  1 board 33  1
```

Fix:

```bash
zcat pinterest.edges.gz | sort | uniq > pinterest.edges
```

**Comment by Refefer** [comment]
Yeah, I've noticed that as well.  The dataset is a literal translation from the npz on kaggle to cloverleaf format, which includes those duplicates - https://www.kaggle.com/datasets/minnieliang/rec-system

Given papers have omitted mention of them, I'm not convinced it's not an error but similarly unsure if it's intentional.  I've chosen to leave it as is :man_shrugging:

**Comment by ghost** [comment]
Aha ok, leaving it then
